### ISSUE TITLE
broken pipe

### ISSUE THREAD

**Issue by Sly777** [mrahman4/aws-ai#1]
Hey Mohamed,

thanks for your plugin but it doesn't work somehow. It always gives "broken pipe" error on AWS post. What do you suggest? I searched on google but I couldn't find anything. Accesskey and secret are normally there.

```
Future<String> _checkImage(String filePath, String SecondPath) {
    File sourceImagefile, targetImagefile; //load source and target images in those File objects
    String accessKey, secretKey, region ; //load your aws account info in those variables

    targetImagefile = File(filePath);
    sourceImagefile = File(SecondPath);

    accessKey = 'xxx';
    secretKey = 'xxx';
    region = 'eu-west-1';

    RekognitionHandler rekognition = new RekognitionHandler(accessKey, secretKey, region);
    Future<String> labelsArray = rekognition.compareFaces(sourceImagefile, targetImagefile);
    return labelsArray;
  }
```

**Comment by mrahman4** [comment]
Can you please try to load image for example

List<int> sourceImageFile.readAsBytesSync();
List<int> targetImageFile.readAsBytesSync();

If images are loaded successfully can you tell me which line return this error

**Comment by Sly777** [comment]
Thanks for your message, @mrahman4. I tested that and here is the result;

```
List a = sourceImagefile.readAsBytesSync();
List b = targetImagefile.readAsBytesSync();

a : size = 9709274
b : size = 9932556
```

and it doesn't give any error. so there is no problem on photos.

as a error, it gives this;

```
I/flutter ( 5778): SocketException: OS Error: Broken pipe, errno = 32, address = rekognition.eu-west-1.amazonaws.com, port = 40322
```

**Comment by mrahman4** [comment]
I believe SocketException is something relate to connection with internet. 

- Can you try different internet connection source
- Can you ensure that images contain faces
- Can you try other services/APIs and see if same error exist

**Comment by Sly777** [comment]
@mrahman4 , I tested it with translate function (with your plugin :) and it works. It returns the translation of a text. On this function, Maybe the problem is photos are bigger than the max limit. But also I'm using the lowest resolution. I tested with a different internet connection and faces (and also without faces too) but doesn't change.

**Comment by mrahman4** [comment]
Can you change the region to us-east-1 and tell me what happen

**Comment by mrahman4** [comment]
Should I close this issue now?

**Comment by Sly777** [comment]
Sorry still I couldn't test it, I will inform you after test

**Comment by mrahman4** [comment]
OK I'll close this issue for now. if you find it still exist you can reopen it again
