### ISSUE TITLE
in face comparison, how to load the image in file object? 

### ISSUE THREAD

**Issue by ShubhraDeshpande** [mrahman4/aws-ai#4]
first of all thank you for a great package: 
issue: 

` import 'package:aws_ai/src/RekognitionHandler.dart';

File sourceImagefile, targetImagefile; //load source and target images in those File objects
String accessKey, secretKey, region ;` 

- We can not set the value of sourceImageFile to image as it requires file object 
- We can not also provide the path to the image because it says "no file exists"

assume that my source and target images are assets/101.jpg and assets/102.jpg please help me set the variable value since there is no other documentation to follow.

**Comment by mrahman4** [comment]
If I understand your issue right.
The point is files that you need to compare usually not in your asset directory, or in this case you are only handle fixed images.
However in all cases (file in assets or outside the app), just load images in asset in file object. Then pass this objects to API
make sense?

**Comment by ShubhraDeshpande** [comment]
unfortunately 
'var sourceImagefile = new File('assets/101.jpg');' 
cannot load the image and I am getting the error of No such file. 
I am just testing the working on images from assets. Can you please help me with it? 

I tried translation, so connection and working of API is smooth, I am just stuck with it. 
Thank you for the warm reply!
